server:
  port: 8090


  
  
resilience4j:
  circuitbreaker:
    instances:
      service1:
       register-health-indicator: true
       ring-buffer-size-in-closed-state: 5
       ring-buffer-size-in-half-open-state: 3
       wait-duration-in-open-state: 50s
       failure-rate-threshold: 50
       event-consumer-buffer-size: 10
       
       
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"  
        
        
info:
  application:
    name: Nkwe Mapoulo                
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TheUser?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: NkweMapoulo@1
    username: root
  jpa:
    hibernate:
      ddl-auto: update        
  application:
    name: USER-SERVICE   